version: '3'
services:     
  db:
    image: databasesql
    build: ./db
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_DATABASE: 'botconfig'
      MYSQL_PASSWORD: 'qwerty'
      MYSQL_ROOT_PASSWORD: 'qwerty'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'qwerty'
      MYSQL_RANDOM_ROOT_PASSWORD: 'qwerty'
    restart: always
    ports: 
      - '3307:3307'