version: '3'
services:     
  app:
    image: api/history
    build: ./app
    ports:
      - '3000:3000'
    volumes: 
      - ./app:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: api/history/database
    build: ./db
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_DATABASE: 'history'
      MYSQL_PASSWORD: '1234567890'
      MYSQL_ROOT_PASSWORD: '1234567890'
      MYSQL_ALLOW_EMPTY_PASSWORD: '1234567890'
      MYSQL_RANDOM_ROOT_PASSWORD: '1234567890'
    restart: always
    ports: 
      - '3307:3307'

volumes:
    db-config:
    db-data:
